spring:
      application:
        name: zipkin-server
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
  instance:
    hostname: localhost